---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php support
    apt:
      name: libapache2-mod-php
      state: latest

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution_version == "CentOS"

  - name: install apache2 package
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: add php support
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"
